### ISSUE TITLE
mini_racer 0.3 cause resque to hang

### ISSUE THREAD

**Issue by braindeaf** [rubyjs/mini_racer#189]
Bizarre situation we've been investigating this week. Our, rather old Rails app

ruby 2.6.6
rails 4.2.11.3
resque 1.27.4

Had issues with trying to kill resque with kill -s QUIT, it simply did nothing (the process never died) and we had workers hang too. Working back through recent upgrades the mini_racer upgrade from 0.2.6 -> 0.3.1 seems to be the cause. I am not sure even how to troubleshoot to give more helpful feedback and this seems more than unlikely to be connected but rolling back every change to this one change is the only way out of resque being seemingly immortal.

I hope this is of interest.

**Comment by tisba** [comment]
Maybe related to https://github.com/rubyjs/mini_racer/issues/170?

**Comment by tisba** [comment]
A lot of fixes and improvements have been done since version 0.3.

Please give recent mini_racer versions a try (0.6.2) and make sure to use `MiniRacer::Platform.set_flags!(:single_threaded)` in case you are running in an environment with forking. For more information see for example #170.

I'm closing this, but please let us know if the issue still persists, @braindeaf!
